/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Cactus = forwardRef(function Cactus(props, ref) {
  const { nodes, materials } = useGLTF('/Cactus.glb');

  return (
    <group ref={ref} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cactus.geometry}
        material={materials.Material}
        scale={[0.046, 0.25, 0.046]}
      />
    </group>
  );
});

useGLTF.preload('/Cactus.glb');
export default Cactus;
