/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Bush = forwardRef((props, ref) => {
  //const group = useRef()
  const { nodes, materials } = useGLTF('/Bush.glb')
  return (
    <group 
      ref={ref} 
      {...props} 
      dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials.Material}
        scale={[1.13, 1.13, 1.13]}
      />
    </group>
  )
})

useGLTF.preload('/Bush.glb')
export default Bush;