/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { forwardRef, useRef, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'

const Bush = forwardRef((props, ref) => {
  //const group = useRef()
  const { nodes, materials } = useGLTF('/Bush.glb')
  
  //const [label, setLabel] = useState(false);
//   <Html>
//   <div class="label"> hi
//   </div>
// </Html>
  return (
    <group 
      
      ref={ref} 
      {...props} 
      dispose={null}>
   
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials.Material}
        scale={[1.13, 1.13, 1.13]}
      />
    </group>
  )
})

useGLTF.preload('/Bush.glb')
export default Bush;