/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Cactus = forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Cactus.glb')
  return (
    <group 
      ref={ref} 
      {...props} 
      dispose={null} 
      >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cactus.geometry}
        material={materials.Material}
        scale={[0.31, 1.46, 0.31]}
      />
    </group>
  )
})

useGLTF.preload('/Cactus.glb')
export default Cactus;