/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const FallingLeaves = forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fallingLeaves.glb')
  console.log(materials)
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={[0.01, 0.01, 0.01]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
      </group>
    </group>
  )
})

useGLTF.preload('/fallingLeaves.glb')
export default FallingLeaves;